##### 下面列举一些常用组函数使用案例

In [2]:
import numpy as np

ndarray1 = np.array([3.5, 1.7, 2.2, -7.8, np.nan, 4.6, -3.4])
ndarray1

array([ 3.5,  1.7,  2.2, -7.8,  nan,  4.6, -3.4])

In [124]:
# abs	计算整数、浮点数的绝对值。
np.abs(ndarray1)

array([ 3.5,  1.7,  2.2,  7.8,  nan,  4.6,  3.4])

In [125]:
# aqrt	计算各元素的平方根。相当于arr ** 0.5
np.square(ndarray1)

array([ 12.25,   2.89,   4.84,  60.84,    nan,  21.16,  11.56])

In [126]:
# sign	计算各元素的正负号,1(正数)、0（零）、-1(负数)
np.sign(ndarray1)

array([  1.,   1.,   1.,  -1.,  nan,   1.,  -1.])

In [127]:
# ceil	计算各元素的celling值，即大于该值的最小整数。
np.ceil(ndarray1)

array([  4.,   2.,   3.,  -7.,  nan,   5.,  -3.])

In [128]:
# floor	计算各元素的floor值，即小于等于该值的最大整数。
np.floor(ndarray1)

array([  3.,   1.,   2.,  -8.,  nan,   4.,  -4.])

In [129]:
# rint	将各元素值四舍五入到最近的整数，保留dtype
np.rint(ndarray1)

array([  4.,   2.,   2.,  -8.,  nan,   5.,  -3.])

In [130]:
# isnan	返回一个表示“那些是NaN（这不是一个数字）”的布尔类型数组.
np.isnan(ndarray1)

array([False, False, False, False,  True, False, False], dtype=bool)

##### 二元运算符

In [141]:
ndarray2 = np.random.randint(1, 20, (4, 5))
ndarray3 = np.random.randint(-10, 10, (4, 5))
ndarray3 = np.where(ndarray3 == 0, 1, ndarray3)

In [142]:
ndarray2

array([[ 8, 13, 18, 12, 11],
       [11, 19, 14,  8, 14],
       [ 8,  6, 19, 19, 16],
       [14,  7,  6,  6,  2]])

In [143]:
ndarray3

array([[  1,   7, -10,  -6,   5],
       [ -5,   2,  -1,   2,   5],
       [  5,   4,  -1,   1,  -1],
       [ -1,  -4,   1,   3,   3]])

In [144]:
# add	将数组中对应的元素相加.
np.add(ndarray2, ndarray3)

array([[ 9, 20,  8,  6, 16],
       [ 6, 21, 13, 10, 19],
       [13, 10, 18, 20, 15],
       [13,  3,  7,  9,  5]])

In [145]:
# subtract	从第一个数组中减去第二个数组中的元素.
np.subtract(ndarray2, ndarray3)

array([[ 7,  6, 28, 18,  6],
       [16, 17, 15,  6,  9],
       [ 3,  2, 20, 18, 17],
       [15, 11,  5,  3, -1]])

In [146]:
# maximum、fmax	从两个数组中取出最大值。fmax将忽略NaN
np.maximum(ndarray2, ndarray3)

array([[ 8, 13, 18, 12, 11],
       [11, 19, 14,  8, 14],
       [ 8,  6, 19, 19, 16],
       [14,  7,  6,  6,  3]])

In [147]:
# mod	元素级的求模计算.
np.mod(ndarray2, ndarray3)

array([[ 0,  6, -2,  0,  1],
       [-4,  1,  0,  0,  4],
       [ 3,  2,  0,  0,  0],
       [ 0, -1,  0,  0,  2]])

In [148]:
# copysign	将第二个数组中的值的符号复制给第一个数组中的值.
np.copysign(ndarray2, ndarray3)

array([[  8.,  13., -18., -12.,  11.],
       [-11.,  19., -14.,   8.,  14.],
       [  8.,   6., -19.,  19., -16.],
       [-14.,  -7.,   6.,   6.,   2.]])

In [149]:
# greater、greater_equal	执行元素级的运算比较，最终产生布尔类型数组。
np.greater(ndarray2, ndarray3)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]], dtype=bool)