In [36]:
import numpy as np

ndarray1 = np.arange(4)
ndarray2 = np.arange(4)
ndarray3 = np.arange(12).reshape((3, 4))

##### 1. append数组中追加元素

In [95]:
# 数组追加一个数值元素
print(ndarray1)
np.append(ndarray1, 100)

[0 1 2 3]


array([  0,   1,   2,   3, 100])

In [96]:
# 在一维数组后追加一维数组
print(ndarray2)
np.append(ndarray1, ndarray2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([ 0,  1,  2,  3,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [97]:
# 在二维数组后追加标量元素
print(ndarray3)
np.append(ndarray3, 100)

[3 4 5]


array([  3,   4,   5, 100])

In [98]:
# append总是返回一维数组
np.append(ndarray1, ndarray3)

array([0, 1, 2, 3, 3, 4, 5])

##### 2. concatenate合并两个数组元素

In [84]:
ndarray4 = np.arange(12).reshape((3, 4))
ndarray4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
# 合并两个一维数组
np.concatenate((ndarray1, ndarray2))

array([0, 1, 2, 3, 0, 1, 2, 3])

In [52]:
# 合并两个二维数组
np.concatenate((ndarray3, ndarray4), axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [53]:
# 合并两个二维数组
np.concatenate((ndarray3, ndarray4), axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

##### 3. delete删除一行或者一列数组元素

In [54]:
ndarray5 = np.arange(20).reshape((4, 5))
ndarray5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [55]:
# 删除第0行元素
np.delete(ndarray5, 0, axis=0)

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [56]:
# 删除第2列元素
np.delete(ndarray5, 1, axis=1)

array([[ 0,  2,  3,  4],
       [ 5,  7,  8,  9],
       [10, 12, 13, 14],
       [15, 17, 18, 19]])

In [58]:
# 删除第0、2、3列元素
np.delete(ndarray5, [0, 2, 3], axis=1)

array([[ 1,  4],
       [ 6,  9],
       [11, 14],
       [16, 19]])

In [60]:
# 使用np.s_[::]创建切片对象
# 删除从1、2列元素
np.delete(ndarray5, np.s_[1:3], axis=1)

array([[ 0,  3,  4],
       [ 5,  8,  9],
       [10, 13, 14],
       [15, 18, 19]])

##### 4. insert插入元素

In [100]:
# 在第2个位置插入元素100
ndarray6 = np.arange(4)
print(ndarray6)
np.insert(ndarray6, 1, 100)

[0 1 2 3]


array([  0, 100,   1,   2,   3])

In [101]:
# 在第3个位置插入两个元素10、20
np.insert(ndarray6, 2, [10, 20])

array([ 0,  1, 10, 20,  2,  3])

In [102]:
# 在第2行插入一行元素
np.insert(ndarray6, 1, np.array([100, 200, 300, 400]), axis=0)

array([  0, 100, 200, 300, 400,   1,   2,   3])

In [103]:
# 在第3列插入一列元素
ndarray7 = np.arange(12).reshape((3, 4))
np.insert(ndarray7, 2, np.array([100, 200, 300]), axis=1)

array([[  0,   1, 100,   2,   3],
       [  4,   5, 200,   6,   7],
       [  8,   9, 300,  10,  11]])