In [1]:
import numpy as np

ndarray1 = np.random.randint(1, 10, (4, 5))
ndarray1

array([[6, 2, 8, 5, 9],
       [1, 3, 7, 7, 7],
       [3, 8, 7, 3, 7],
       [4, 7, 5, 7, 3]])

##### 1. sum求元素和

In [2]:
# 0-列 1-行
# sum-计算所有元素和
np.sum(ndarray1)

109

In [3]:
# sum-计算每一列的元素和
np.sum(ndarray1, axis=0)

array([14, 20, 27, 22, 26])

In [4]:
# sum-计算每一行的元素和
np.sum(ndarray1, axis=1)

array([30, 25, 28, 26])

##### 2. argmax求最大值索引

In [5]:
# argmax-默认情况下按照一维数组索引
np.argmax(ndarray1)

4

In [6]:
# argmax-统计每一列最大
np.argmax(ndarray1, axis=0)

array([0, 2, 0, 1, 0])

In [7]:
# argmax-统计每一行最大
np.argmax(ndarray1, axis=1)

array([4, 2, 1, 1])

##### 3. mean求平均数

In [8]:
# mean-求所有元素的平均值
np.mean(ndarray1)

5.4500000000000002

In [9]:
# mean-求每一列元素的平均值
np.mean(ndarray1, axis=0)

array([ 3.5 ,  5.  ,  6.75,  5.5 ,  6.5 ])

In [10]:
# mean-求每一行元素的平均值
np.mean(ndarray1, axis=1)

array([ 6. ,  5. ,  5.6,  5.2])

##### 4.  cumsum求元素累计和

In [11]:
# cumsum-前面元素的累计和
np.cumsum(ndarray1)

array([  6,   8,  16,  21,  30,  31,  34,  41,  48,  55,  58,  66,  73,
        76,  83,  87,  94,  99, 106, 109])

In [12]:
# cumsum-每一列元素的累计和
np.cumsum(ndarray1, axis=0)

array([[ 6,  2,  8,  5,  9],
       [ 7,  5, 15, 12, 16],
       [10, 13, 22, 15, 23],
       [14, 20, 27, 22, 26]])

In [13]:
# cumsum-每一行元素的累计和
np.cumsum(ndarray1, axis=1)

array([[ 6,  8, 16, 21, 30],
       [ 1,  4, 11, 18, 25],
       [ 3, 11, 18, 21, 28],
       [ 4, 11, 16, 23, 26]])