In [42]:
# pandas 可以同时处理文本类型和数字, numpy 主要是处理数学计算
# 嵌入一些 matplotlib 相关api
# Hadoop Spark Storm 如果数据只有几GB，甚至1~2TB，那么pandas也是处理数据的最好选择
# 特殊的数据结构 DataFrame and  Series
# 行索引(主键id) 和 列索引(列名)
import pandas as pd
import numpy as np
b = np.arange(10).reshape((2,5))  # 改变形状
print(b)
a = np.arange(10) # => np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
df = pd.DataFrame(a,columns=["年龄"],index=["赤","橙","黄","绿","青", "赤","橙","黄","绿","青"])
print(df)
df = pd.DataFrame(b,index=["销量","方差"])
print(df)
df = pd.DataFrame(np.array([[1,2,3],[4,5,6]]),
                 index=["第一行","第二行"]
                 ,columns=["第一列","第二列","第三列"]) # 手动创建2行3列
print(df)
stock = np.random.normal(0,1,(500,504))  # 生成期望为0 方差为1的 正态分布随机数
len(stock[0])

print(stock.shape)  # (500,504)
# 时间序列  生成DatetimeIndex对象  freq="D" 周期是Day
# [,,,,] dtype='datetime64[ns]', length=500, freq='D'
date_columns = pd.date_range(start="2018-01-01",periods=stock.shape[1],freq="B")  # periods=50,freq="Y"
print(date_columns)
# help(pd.date_range)
stock_df = pd.DataFrame(stock,index=["第{}行".format(i) for i in range(1,stock.shape[0]+1)],
                       columns=date_columns)  # ["第{}列".format(i) for i in range(1,stock.shape[1]+1)]
stock_df_T = stock_df.T  # 矩阵转换 横向转纵向, 行变列, 列变行
# print(stock_df_T)
# pd.DataFrame()
# 行索引，表明不同行，横向索引，叫index，0轴，axis=0
# 列索引，表名不同列，纵向索引，叫columns，1轴，axis=1

###########  属性  ########
stock_df.dtypes   # numpy 没有爱斯 dtype    2018-01-01    float64  
stock_df.shape    # 形状  (500, 504)
stock_df.index    # Index的对象,行索引的对象
stock_df.index.values  # 获取行索引的值
stock_df.columns  # 获取columns对象.列索引对象
stock_df.columns.values  # 获取列索引的值
# 直接获取data
print(type(stock_df.values))  # 还是numpy的s<class 'numpy.ndarray'>
stock_df.head(10)  # 默认不传是5
stock_df.tail(10)  # 默认不传是5
# stock_df.ndim  # 2维数组, 返回2
""" Series 只有行没有列,通俗的说就是DataFrame的某一列"""

print(type(stock_df["2018-01-01"])) # <class 'pandas.core.series.Series'>
""" 字典的形式创建DataFrame  """
dict_create = pd.DataFrame({1:["mmd","18","man"],2:["bcz","24","woman"]})
# print(stock_df["2018-01-01"])  # 默认取一列
# 手动创建Series 因为可以理解为一个主键一个值,索引可以通过字典的形式来创建Series
ss = pd.Series({1:"mmd",2:"24years old",3:"man"})
# ss.index  # Int64Index([1, 2, 3], dtype='int64')  ss.columns 不存在
# ss[1:3]
# ss["name"]  # 可以通过索引key(行的键针对Series)获取也可以通过下标获取
# pandas 读csv
names=["第{}个".format(i) for i in range(8)]
read_data = pd.read_csv("1.csv",names=names)  # 会默认加入行索引和列索引(没有的前提下)
""" index_col = "date"  表示 忽略行索引date"""
# print(read_data)
# print(read_data.columns)
# print(read_data.index)
# print(read_data.index)
# help(pd.read_csv)
"""
DataFrame.to_csv(path_or_buf=None, sep=', ’, columns=None, 
header=True, index=True, index_label=None, mode='w', encoding=None, rue)
    path_or_buf : string or file handle, default None
    sep : character, default ‘,’
    columns : sequence, optional
    Columns to write，写入文件时指定新的列索引
    header : boolean or list of string, default True,是否写进列索引值
    index : boolean, default True，是否写进行索引值
    index_label : string or sequence, or False, default None，是否将行索引当成
一列数据
"""
"""  hdf文件(.h5)数据里大,支持压缩,跨平台,blosc  读不进去,pip install tables"""
# read_data.to_csv("6666.csv",read_data)  # index=False 写作操作
# pd.read_csv("a.csv",index_col="Unnamed: 1") # 读作操作!!  读取指定某一列为行索引
# h = pd.read_hdf("",key="") 读的时候多了个key可不传  h.to_hdf(key="test_key")  # 必须有key!!!!!

# #key-value存储
# DataFrame.to_hdf(path_or_buf=None)
# #普通方式存储
# h5 = pd.HDFStore('t1.h5','w')
# h5['data'] = a   # "data" 可以自己命名为其他的
# h5.close()
# #压缩方式存储
# h5 = pd.HDFStore('t2.h5','w', complevel=4, complib='blosc')  # -> complevel 压缩界别  complib 压缩方式
# h5['data'] = a
# h5.close()
""" 如果要索引数据  必须先写列(索引,看到什么就索引什么)后写行(索引,看到什么就索引什么) """
# print(read_data)
# read_data["产品名称"][10]   # 先列后行
read_data["第0个"][1]  # 先列后行
read_data[["第0个","第1个","第2个","第3个"][0:6]]  # 先列后行 ,二维获取
"""stock_df.index = pd.to_datetime(stock.index)   一种方法"""
read_data["第0个"][1]

# 只能按行或列的名称进行操作
# 先行后列
# print(read_data.loc[0:3,"第0个":"第3个"])   # 0到3行, 0到3列                第一种写法
# read_data.loc[[0,1,2,3],["第0个","第1个","第2个","第3个"]] # 0到3行, 0到3列  第二种写法
# read_data.iloc[0:3,0:3]
# read_data.iloc[0:3,0:3]                # 第一种写法
# read_data.iloc[[0,1,2,3],[0,1,2,3]]    # 第二种写法
# read_data.ix[0:3,"第0个":"第3个"]        # 过时的api 不建议,,,,,,, 组合使用
# read_data.ix[[0,1,2,3],["第0个","第1个","第2个","第3个"]]  # 过时api 第二种写法
# read_data.iloc[0:4,:].loc[:,"第0个":"第3个"]  # 自己的写法 结合使用
# 必须传入基准列名称by=""
read_data.sort_values(by=["第4个"],ascending=False)  # by=[] or string 
# read_data()
read_data.sort_index(ascending=False)  # 行排序




[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
   年龄
赤   0
橙   1
黄   2
绿   3
青   4
赤   5
橙   6
黄   7
绿   8
青   9
    0  1  2  3  4
销量  0  1  2  3  4
方差  5  6  7  8  9
     第一列  第二列  第三列
第一行    1    2    3
第二行    4    5    6
(500, 504)
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-08', '2018-01-09', '2018-01-10',
               '2018-01-11', '2018-01-12',
               ...
               '2019-11-22', '2019-11-25', '2019-11-26', '2019-11-27',
               '2019-11-28', '2019-11-29', '2019-12-02', '2019-12-03',
               '2019-12-04', '2019-12-05'],
              dtype='datetime64[ns]', length=504, freq='B')
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>


第0个              第1个             第2个     第3个  \
177            水果系列 T 恤 「两款可选」  Into This Dream             橙子M   499.0   
176            水果系列 T 恤 「两款可选」  Into This Dream             橙子S   499.0   
175            水果系列 T 恤 「两款可选」  Into This Dream             柠檬M   499.0   
174            水果系列 T 恤 「两款可选」  Into This Dream             柠檬S   499.0   
173            水果系列 T 恤 「两款可选」  Into This Dream             西瓜M   499.0   
172            水果系列 T 恤 「两款可选」  Into This Dream             西瓜S   499.0   
171            水果系列 T 恤 「两款可选」  Into This Dream             香梨M   499.0   
170            水果系列 T 恤 「两款可选」  Into This Dream             香梨S   499.0   
169            水果系列 T 恤 「三款可选」  Into This Dream             樱桃M   499.0   
168            水果系列 T 恤 「三款可选」  Into This Dream             樱桃S   499.0   
167            水果系列 T 恤 「三款可选」  Into This Dream             桃子M   499.0   
166            水果系列 T 恤 「三款可选」  Into This Dream             桃子S   499.0   
165            水果系列 T 恤 「三款可选」  Into This Dream             草莓M   499.0   
164            水果系列 T 恤 「三款可选」  Into This Dream             草莓S   499.0   
163             风雅迷人系列百褶裙-浅杏灰色  Into This Dream               L   899.0   
162             风雅迷人系列百褶裙-浅杏灰色  Into This Dream               M   899.0   
161             风雅迷人系列百褶裙-浅杏灰色  Into This Dream               S   899.0   
160              风雅迷人系列百褶裙-深蓝色  Into This Dream               L   899.0   
159              风雅迷人系列百褶裙-深蓝色  Into This Dream               M   899.0   
158              风雅迷人系列百褶裙-深蓝色  Into This Dream               S   899.0   
157              风雅迷人系列百褶裙-豆沙色  Into This Dream               L   899.0   
156              风雅迷人系列百褶裙-豆沙色  Into This Dream               M   899.0   
155              风雅迷人系列百褶裙-豆沙色  Into This Dream               S   899.0   
154      巴黎女孩的小光芒 Akoya 单颗珍珠项链  Into This Dream               l  1080.0   
153        It's mine 缎面凉拖鞋-复古绿          Camelia              36  1269.0   
152         法式系列-简洁七分袖连衣裙 白底方点  Into This Dream               S  1129.0   
151    「出游季」经典 T 恤系列-圆领款 黑+白两色  Into This Dream               L   838.0   
150    「出游季」经典 T 恤系列-圆领款 黑+白两色  Into This Dream               M   838.0   
149    「出游季」经典 T 恤系列-圆领款 黑+白两色  Into This Dream               S   838.0   
148        「出游季」经典 T 恤系列-拼色条纹款  Into This Dream               M   419.0   
..                         ...              ...             ...     ...   
29         柔美系列-蕾丝边饰长款连衣裙 白底黑点  Into This Dream               S  2119.0   
28                    褶皱迷你短连衣裙  Into This Dream               L  1570.0   
27                    褶皱迷你短连衣裙  Into This Dream               M  1570.0   
26                    褶皱迷你短连衣裙  Into This Dream               S  1570.0   
25                    中高腰条纹阔腿裤  Into This Dream               L  1280.0   
24                    中高腰条纹阔腿裤  Into This Dream               M  1280.0   
23                    中高腰条纹阔腿裤  Into This Dream               S  1280.0   
22                    松紧高腰条纹短裤  Into This Dream               L   990.0   
21                    松紧高腰条纹短裤  Into This Dream               M   990.0   
20                    松紧高腰条纹短裤  Into This Dream               S   990.0   
19                不对称荷叶边上衣 黑白格  Into This Dream               M  1280.0   
18                不对称荷叶边上衣 黑白格  Into This Dream               S  1280.0   
17                 不对称荷叶边上衣 白色  Into This Dream               L  1280.0   
16                 不对称荷叶边上衣 白色  Into This Dream               M  1280.0   
15                 不对称荷叶边上衣 白色  Into This Dream               S  1280.0   
14               度假柔美风情连衣裙  红色  Into This Dream               L  1570.0   
13               度假柔美风情连衣裙  红色  Into This Dream               M  1570.0   
12               度假柔美风情连衣裙  红色  Into This Dream               S  1570.0   
11                 不对称拼接迷你短连衣裙  Into This Dream               L  1570.0   
10                 不对称拼接迷你短连衣裙  Into This Dream               M  1570.0   
9                  不对称拼接迷你短连衣裙  Into This Dream               S  1570.0   
8                      不对称褶皱上衣  Into This Dream     