In [67]:
# pandas 可以同时处理文本类型和数字, numpy 主要是处理数学计算
# 嵌入一些 matplotlib 相关api
# Hadoop Spark Storm 如果数据只有几GB，甚至1~2TB，那么pandas也是处理数据的最好选择
# 特殊的数据结构 DataFrame and  Series
# 行索引(主键id) 和 列索引(列名)
import pandas as pd
import numpy as np
b = np.arange(10).reshape((2,5))  # 改变形状
print(b)
a = np.arange(10) # => np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
df = pd.DataFrame(a,columns=["年龄"],index=["赤","橙","黄","绿","青", "赤","橙","黄","绿","青"])
print(df)
df = pd.DataFrame(b,index=["销量","方差"])
print(df)
df = pd.DataFrame(np.array([[1,2,3],[4,5,6]]),
                 index=["第一行","第二行"]
                 ,columns=["第一列","第二列","第三列"]) # 手动创建2行3列
print(df)
stock = np.random.normal(0,1,(500,504))  # 生成期望为0 方差为1的 正态分布随机数
len(stock[0])

print(stock.shape)  # (500,504)
# 时间序列  生成DatetimeIndex对象  freq="D" 周期是Day
# [,,,,] dtype='datetime64[ns]', length=500, freq='D'
date_columns = pd.date_range(start="2018-01-01",periods=stock.shape[1],freq="B")  # periods=50,freq="Y"
print(date_columns)
# help(pd.date_range)
stock_df = pd.DataFrame(stock,index=["第{}行".format(i) for i in range(1,stock.shape[0]+1)],
                       columns=date_columns)  # ["第{}列".format(i) for i in range(1,stock.shape[1]+1)]
stock_df_T = stock_df.T  # 矩阵转换 横向转纵向, 行变列, 列变行
# print(stock_df_T)
# pd.DataFrame()
# 行索引，表明不同行，横向索引，叫index，0轴，axis=0
# 列索引，表名不同列，纵向索引，叫columns，1轴，axis=1

###########  属性  ########
stock_df.dtypes   # numpy 没有爱斯 dtype    2018-01-01    float64  
stock_df.shape    # 形状  (500, 504)
stock_df.index    # Index的对象,行索引的对象
stock_df.index.values  # 获取行索引的值
stock_df.columns  # 获取columns对象.列索引对象
stock_df.columns.values  # 获取列索引的值
# 直接获取data
print(type(stock_df.values))  # 还是numpy的s<class 'numpy.ndarray'>
stock_df.head(10)  # 默认不传是5
stock_df.tail(10)  # 默认不传是5
# stock_df.ndim  # 2维数组, 返回2
""" Series """


[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
   年龄
赤   0
橙   1
黄   2
绿   3
青   4
赤   5
橙   6
黄   7
绿   8
青   9
    0  1  2  3  4
销量  0  1  2  3  4
方差  5  6  7  8  9
     第一列  第二列  第三列
第一行    1    2    3
第二行    4    5    6
(500, 504)
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-08', '2018-01-09', '2018-01-10',
               '2018-01-11', '2018-01-12',
               ...
               '2019-11-22', '2019-11-25', '2019-11-26', '2019-11-27',
               '2019-11-28', '2019-11-29', '2019-12-02', '2019-12-03',
               '2019-12-04', '2019-12-05'],
              dtype='datetime64[ns]', length=504, freq='B')
<class 'numpy.ndarray'>


2018-01-01  2018-01-02  2018-01-03  2018-01-04  2018-01-05  2018-01-08  \
第491行    1.753754    1.192859   -0.504306    1.152960    0.238638   -0.076080   
第492行   -0.663345    1.367350   -1.358157    1.248687    1.499249    2.122900   
第493行    0.692549   -0.521318   -0.370647    1.273704    1.035764   -2.176629   
第494行    0.658353    0.773996    0.631276    2.452384   -0.515105   -0.883903   
第495行   -1.597241    0.301315    1.163199    0.057724    1.303713   -0.235005   
第496行   -0.201349   -1.681932    0.542180    0.442236   -0.906708   -0.498795   
第497行   -2.710172   -1.800222   -0.209080   -0.343272   -0.222612    0.604203   
第498行   -0.321363    0.751390    0.406918    1.379429   -1.326226    0.003705   
第499行   -0.226526    1.650762   -0.625959    2.011829    0.689906    0.303934   
第500行   -1.448731    2.015488   -0.075708   -0.132770   -0.469135    0.947930   

       2018-01-09  2018-01-10  2018-01-11  2018-01-12     ...      2019-11-22  \
第491行   -0.845187   -0.711756   -1.410549   -0.247803     ...       -0.166050   
第492行    0.271690    3.036742    0.217805   -1.047250     ...       -1.915922   
第493行    0.981501   -0.111322    0.396011   -1.078663     ...        0.104918   
第494行    0.104755   -0.025679    0.165682   -1.216247     ...        1.696972   
第495行   -0.403113    1.069981   -1.651475    0.278121     ...       -0.577609   
第496行    0.228003   -0.401307    0.306430    0.621763     ...        0.535884   
第497行    0.989295   -1.387174   -0.483944    1.414376     ...        1.240854   
第498行    1.021353    0.853538   -0.091232    0.795921     ...        0.270147   
第499行   -0.070346   -0.342330    0.182014   -1.676002     ...        0.182207   
第500行   -1.647083    2.449456   -1.548605   -0.424463     ...        1.316218   

       2019-11-25  2019-11-26  2019-11-27  2019-11-28  2019-11-29  2019-12-02  \
第491行   -0.833217    0.497622    1.608319    2.416011    0.148819    1.128055   
第492行   -0.787433   -0.324278    0.340185    0.157982   -1.180497   -0.447216   
第493行   -0.615601   -2.541270   -1.438474   -2.105247    0.964138   -1.903776   
第494行   -0.944341    0.196756   -1.382562    0.731431   -0.322171    0.023659   
第495行   -0.856895   -0.281174   -1.177930   -0.671685   -0.777905    1.171131   
第496行   -1.329751   -2.450402   -1.186731    1.528962    1.228924    0.506901   
第497行    0.030727   -1.178734   -0.597260   -0.092197    0.051969    0.653497   
第498行    1.171370    1.930608    0.447396   -0.090879   -1.235892    0.995784   
第499行   -1.420268   -0.627634    1.738871   -0.505448    1.866187    1.021157   
第500行   -0.473012    0.929994   -1.362186   -0.543910   -0.846463    0.535945   

       2019-12-03  2019-12-04  2019-12-05  
第491行    0.010510    0.256431    0.163883  
第492行    0.711677    1.090347    0.037375  
第493行   -0.915614    0.118909   -0.364200  
第494行    0.714588    0.845354    0.141272  
第495行    0.419686    2.426985    0.051360  
第496行    0.294104    0.983937   -0.242936  
第497行   -0.455573    0.236744    1.279407  
第498行    1.286951    0.881618    0.277004  
第499行   -0.078348    0.159397    1.798010  
第500行    0.368455    0.365519    1.425736  

[10 rows x 504 columns]