In [46]:
# pandas 可以同时处理文本类型和数字, numpy 主要是处理数学计算
# 嵌入一些 matplotlib 相关api
# Hadoop Spark Storm 如果数据只有几GB，甚至1~2TB，那么pandas也是处理数据的最好选择
# 特殊的数据结构 DataFrame and  Series
# 行索引(主键id) 和 列索引(列名)
import pandas as pd
import numpy as np
b = np.arange(10).reshape((2,5))  # 改变形状
print(b)
a = np.arange(10) # => np.array([1,2,3,4,5,6,7,8,9,10])
print(a)
df = pd.DataFrame(a,columns=["年龄"],index=["赤","橙","黄","绿","青", "赤","橙","黄","绿","青"])
print(df)
df = pd.DataFrame(b,index=["销量","方差"])
print(df)
df = pd.DataFrame(np.array([[1,2,3],[4,5,6]]),
                 index=["第一行","第二行"]
                 ,columns=["第一列","第二列","第三列"]) # 手动创建2行3列
print(df)
stock = np.random.normal(0,1,(500,504))  # 生成期望为0 方差为1的 正态分布随机数
len(stock[0])

print(stock.shape)  # (500,504)
# 时间序列  生成DatetimeIndex对象  freq="D" 周期是Day
# [,,,,] dtype='datetime64[ns]', length=500, freq='D'
date_columns = pd.date_range(start="2018-01-01",periods=stock.shape[1],freq="B")  # periods=50,freq="Y"
print(date_columns)
# help(pd.date_range)
stock_df = pd.DataFrame(stock,index=["第{}行".format(i) for i in range(1,stock.shape[0]+1)],
                       columns=date_columns)  # ["第{}列".format(i) for i in range(1,stock.shape[1]+1)]
stock_df_T = stock_df.T  # 矩阵转换 横向转纵向, 行变列, 列变行
# print(stock_df_T)
# pd.DataFrame()
# 行索引，表明不同行，横向索引，叫index，0轴，axis=0
# 列索引，表名不同列，纵向索引，叫columns，1轴，axis=1

###########  属性  ########
stock_df.dtypes   # numpy 没有爱斯 dtype    2018-01-01    float64  
stock_df.shape    # 形状  (500, 504)
stock_df.index    # Index的对象,行索引的对象
stock_df.index.values  # 获取行索引的值
stock_df.columns  # 获取columns对象.列索引对象
stock_df.columns.values  # 获取列索引的值
# 直接获取data
print(type(stock_df.values))  # 还是numpy的s<class 'numpy.ndarray'>
stock_df.head(10)  # 默认不传是5
stock_df.tail(10)  # 默认不传是5
# stock_df.ndim  # 2维数组, 返回2
""" Series 只有行没有列,通俗的说就是DataFrame的某一列"""

print(type(stock_df["2018-01-01"])) # <class 'pandas.core.series.Series'>
""" 字典的形式创建DataFrame  """
dict_create = pd.DataFrame({1:["mmd","18","man"],2:["bcz","24","woman"]})
# print(stock_df["2018-01-01"])  # 默认取一列
# 手动创建Series 因为可以理解为一个主键一个值,索引可以通过字典的形式来创建Series
ss = pd.Series({1:"mmd",2:"24years old",3:"man"})
# ss.index  # Int64Index([1, 2, 3], dtype='int64')  ss.columns 不存在
# ss[1:3]
# ss["name"]  # 可以通过索引key(行的键针对Series)获取也可以通过下标获取
# pandas 读csv
names=["第{}个".format(i) for i in range(8)]
read_data = pd.read_csv("1.csv",names=names)  # 会默认加入行索引和列索引(没有的前提下)
""" index_col = "date"  表示 忽略行索引date"""
# print(read_data)
# print(read_data.columns)
# print(read_data.index)
# print(read_data.index)
# help(pd.read_csv)
"""
DataFrame.to_csv(path_or_buf=None, sep=', ’, columns=None, 
header=True, index=True, index_label=None, mode='w', encoding=None, rue)
    path_or_buf : string or file handle, default None
    sep : character, default ‘,’
    columns : sequence, optional
    Columns to write，写入文件时指定新的列索引
    header : boolean or list of string, default True,是否写进列索引值
    index : boolean, default True，是否写进行索引值
    index_label : string or sequence, or False, default None，是否将行索引当成
一列数据
"""
"""  hdf文件(.h5)数据里大,支持压缩,跨平台,blosc  读不进去,pip install tables"""
# read_data.to_csv("6666.csv",read_data)  # index=False 写作操作
# pd.read_csv("a.csv",index_col="Unnamed: 1") # 读作操作!!  读取指定某一列为行索引
# h = pd.read_hdf("",key="") 读的时候多了个key可不传  h.to_hdf(key="test_key")  # 必须有key!!!!!

# #key-value存储
# DataFrame.to_hdf(path_or_buf=None)
# #普通方式存储
# h5 = pd.HDFStore('t1.h5','w')
# h5['data'] = a   # "data" 可以自己命名为其他的
# h5.close()
# #压缩方式存储
# h5 = pd.HDFStore('t2.h5','w', complevel=4, complib='blosc')  # -> complevel 压缩界别  complib 压缩方式
# h5['data'] = a
# h5.close()
""" 如果要索引数据  必须先写列(索引,看到什么就索引什么)后写行(索引,看到什么就索引什么) """
# print(read_data)
# read_data["产品名称"][10]   # 先列后行 必须一维!!!!!!!!!!!
read_data["第0个"][1]  # 先列后行
read_data[["第0个","第1个","第2个","第3个"][0:3]]  # xxxxxxx错误写法  无此写法 逗号只有loc写法
# read_data[0:5,0:3]                              # xxxxxxxx错误写法 无此写法 纯索引只能[:5][:3]  也是错误写法!!!!
read_data[["第0个","第1个"]]  # [["列名",,]][:3]  or [["列名",,]]["横向索引名"]

"""stock_df.index = pd.to_datetime(stock.index)   一种处理索引错误方法"""
# print(read_data[["第0个","第1个"]])  # 多个就是列表
# read_data["第0个"][1:5]
# read_data[["第0个"][4:]]


# 只能按行或列的名称进行操作
# 先行后列   loc支持逗号写法
# print(read_data.loc[0:3,"第0个":"第3个"])   # 0到3行, 0到3列                第一种写法
# read_data.loc[[0,1,2,3],["第0个","第1个","第2个","第3个"]] # 0到3行, 0到3列  第二种写法
# read_data.iloc[0:3,0:3]
# read_data.iloc[0:3,0:3]                # 第一种写法
# read_data.iloc[[0,1,2,3],[0,1,2,3]]    # 第二种写法
# read_data.ix[0:3,"第0个":"第3个"]        # 过时的api 不建议,,,,,,, 组合使用
# read_data.ix[[0,1,2,3],["第0个","第1个","第2个","第3个"]]  # 过时api 第二种写法
# read_data.iloc[0:4,:].loc[:,"第0个":"第3个"]  # 自己的写法 结合使用
# 必须传入基准列名称by=""
# read_data.sort_values(by=["第4个"],ascending=False)  # by=[] or string 
# read_data()
# read_data.sort_index(ascending=False)  # 默认行排序 ,用的相对较少
# read_data.describe()
# read_data.mean()  # 默认展示所有列的平均值
# read_data.mean()  # axis=0 or 1 统计 0 轴 or 1轴  强制取行
# read_data["第4个"][1:].idxmin()  # argmin()
# read_data["第4个"][1:].idxmax()  # argmax()
# """ df[[column]] = df[[column]].astype(type) 转换类型 """
# temp = read_data["第4个"][1:].astype(np.float)
# temp = read_data[["第3个"]]#[1:].astype(np.float)
# temp = read_data[["第3个","第4个"][0:6]]# [1:].astype(np.float)

# temp
# print(type(temp))  # <class 'pandas.core.series.Series'>  字典取法即可
# plt =temp.cumsum().plot()  # 当做正增负数减
# read_data[["多列名"]].cumsum() 累计统计和  read_data["单列"].cumsum()
# .cumprod()  前n个数的乘积 
# .cummax() 前n个数的最大值
# .cummin() 前n个数的最小值
# print(type(plt))  # <class 'matplotlib.axes._subplots.AxesSubplot'>
# stock_df[stock_df["2018-01-01"]>0]
read_data["第3个"]
test_data =  pd.DataFrame(np.array([[1,2,3],[4,5,6]]))
test_data =pd.DataFrame(np.array([[1,2,3],[4,5,6]]),
                 index=["第一行","第二行"]
                 ,columns=["第一列","第二列","第三列"]) # 手动创建2行3列
print(test_data)
test_data[test_data["第一列"]>1]   # 筛选出第一列大于1的一行数据
test_data[(test_data["第一列"]>1) & (test_data["第一列"]<5)] # 筛选出第一列大于1并且小于5的的一行数据
test_data[(test_data["第一列"]>1) | (test_data["第一列"]<5)] # 筛选出第一列大于1or小于5的的一行数据IMDB-Movie-Data.csv

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4 5 6 7 8 9]
   年龄
赤   0
橙   1
黄   2
绿   3
青   4
赤   5
橙   6
黄   7
绿   8
青   9
    0  1  2  3  4
销量  0  1  2  3  4
方差  5  6  7  8  9
     第一列  第二列  第三列
第一行    1    2    3
第二行    4    5    6
(500, 504)
DatetimeIndex(['2018-01-01', '2018-01-02', '2018-01-03', '2018-01-04',
               '2018-01-05', '2018-01-08', '2018-01-09', '2018-01-10',
               '2018-01-11', '2018-01-12',
               ...
               '2019-11-22', '2019-11-25', '2019-11-26', '2019-11-27',
               '2019-11-28', '2019-11-29', '2019-12-02', '2019-12-03',
               '2019-12-04', '2019-12-05'],
              dtype='datetime64[ns]', length=504, freq='B')
<class 'numpy.ndarray'>
<class 'pandas.core.series.Series'>
     第一列  第二列  第三列
第一行    1    2    3
第二行    4    5    6


第一列  第二列  第三列
第一行    1    2    3
第二行    4    5    6

In [61]:
# 空值  NaN  float 类型  
""" 删除  or  填充 """
print(type(np.nan)) # <class 'float'>
movie = pd.read_csv("IMDB-Movie-Data.csv")
# movie     # 第7行 Revenue NaN 营收,财政收入
# movie.dropna(axis=1)  # 哪一列有空 删除这一行
# movie.dropna(inplace=True)  # 哪一列有空 并且这一列没什么分析的必要
# movie.fillna(0)  # 可以默认填充0
average = movie["Revenue (Millions)"].mean()  # 均值
movie.fillna(average,inplace=False)  # 填充均值对原先无影响
movie.fillna(average,inplace=True)  # 填充均值对原先有影响,真正修改元数据  通用方式 movie = .....
# 不是NaN 的 特殊符号 ,
#  处理这种空值 
#  1.把他变成 NaN
#  movie.


pd.isnull(movie)




<class 'float'>


Rank Title Genre Description Director Actors  Year  Runtime (Minutes)  \
0     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
1     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
2     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
3     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
4     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
5     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
6     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
7     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
8     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
9     NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
10    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
11    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
12    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
13    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
14    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
15    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
16    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
17    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
18    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
19    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
20    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
21    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
22    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
23    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
24    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
25    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
26    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
27    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
28    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
29    NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
..    ...   ...   ...         ...      ...    ...   ...                ...   
970   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
971   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
972   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
973   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
974   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
975   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
976   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
977   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
978   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
979   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
980   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
981   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
982   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
983   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
984   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
985   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
986   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
987   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
988   NaN   NaN   NaN         NaN      NaN    NaN   NaN                NaN   
989   NaN   NaN   NaN      