In [2]:
import random
import time
import numpy as np
import numpy
a = []
for i in range(10000000):
    a.append(random.random())

t1 = time.time()
sum1=sum(a)
t2=time.time()
b = numpy.array(a)
t4 = time.time()
sum3 = numpy.sum(b)
t5 = time.time()
print(t2-t1,t5-t4)

# help(numpy.sum)

0.08375287055969238 0.02260303497314453


In [30]:
np.sum([1.5,2.5])
np.sum([1.5,2.5],dtype=np.int32)  # 先四舍五入再计算
np.sum([[0,1],[2,3.1]],dtype=np.int32)# 也可以是字符串 dtype = 'i2' -> int 16  'i4' -> int 32 'i8' -> int 64
print(np.sum([[1,2],[3,4]],axis=0))  # 列相加,第一个加第一个   1轴竖着的

print(np.sum([[1,2],[3,4]],axis=1))  # 行相加 列表内部相加  0轴横着的
res = np.array(0)
print(res.shape)
res = np.array([1,2,3,4])  # 1 维数组
print(res.shape)  # (4,)   
res = np.array([[1,2],[3,4]])
# print(res[1][0])
# print(res.shape) #  (2, 2)  2 行 2 列   2维数组
res = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])  
print('形状',res.shape) #  (2, 2, 3)  2块2行3列  3维数组  看图
print(res)
type(res)
print(" 行数-->", res.shape[0])
print(" dtype-----> ",res.dtype)  # int64 类型
print(" 维度------>",res.ndim)  # 返回维度
print(" size----->",res.size)  # 内层元素数量
# help(res.size)
# print(res.flags)
# help(res.flags)
np.random.randint(10)  # int 类型 随机数
np.random.uniform(10)  # float 类型  随机数
np.random.uniform(0,10,100)   # 0到10 100个 float 随机数
np.random.uniform(0,10,(2,3))  # 生成2行3列的 float 随机数
# np.random.random(10)
# 生成一个符合正态分布的多维数据
np.random.normal(0,1,size=(3,5))  # 创建标准正态分布的3行5列的数据  size 就是shape的含义
np.random.standard_normal(size=(3,5))  # 直接创建符合标准正态分布的3行5列的数据 size 就是 shape的含义
# 生成500个股票2年随机数据
stock_data = np.random.normal(0,1,size=(500,252*2))
stock_data[0][:100]  # 第一个股票的前100个
stock_data[0:5][:100]  # 前5个股票的前100个
stock_data[:5,:100]
docker = stock_data[0:5,0:100].copy()  # copy指定范围然后判断条件
# print(docker[docker[0:5,0:100]>0])
"""as type 修改类型"""
np.unique(stock_data.astype(np.int64))


# bool_b = np.all(stock_data>-100)  # 判断里面所有元素是否都大于0  or 都大于-100
# np.unique(stock_data)
# help(np.unique)
# stock_data[stock_data>0]  # 取符合条件的数据 转换为一维
# # stock_data[:10][:200][stock_data>0]
# res = np.round(stock_data,2)  # n维数组四舍五入
# res = stock_data.astype(np.float16)  # n维数组元素强制转换类型
# # res = stock_data.reshape((1,1))
# res = np.array([[1,2,3]])
# res2 = res.reshape((1,3))
# res
# res2
aa = np.array([[1,2,3],[4,5,6]])
print(aa[:2,:2])  # 先行后列
print("=======")
print(stock_data.shape)
stock_data[0:5,0:10]
stock_data[0:5][0:10]
stock_data[:,0:2]   # 所有行只要前2列 
stock_data[:2,:]    # 所有列只要前2行
stock_data[[0,1,2,3,4,5]][0:3]     # 取5列3行
stock_data[0:5,0:3]     # 取5列3行





[4 6]
[3 7]
()
(4,)
形状 (2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
 行数--> 2
 dtype----->  int64
 维度------> 3
 size-----> 12
[[1 2]
 [4 5]]
(500, 504)


array([[-0.31170748, -0.02902754, -0.34776164],
       [ 0.01356558, -0.36383586,  0.13331538],
       [ 0.03083632, -0.63681273,  1.46847983],
       [-0.87679025, -0.54192134, -1.2905889 ],
       [ 1.06543664,  0.99118431, -1.24206399]])

In [3]:
import numpy as np
# 创建的数组都是(float) 类型  有点的都是float类型
a=np.ones(shape=(2,3))  # [1.0,1.0]
# a=np.ones(shape=(2,3),dtype=np.float32,order="C")
b=np.zeros(shape=(3,2))
# print(a)
# print(a.dtype)  # float32 
# print(a.flags)
# print(a[1][1])  # 1.0 
# print(b[0][0])  # 0.0
c = np.empty(shape=(2,3))  # 创建空的
c = np.eye(5)
c = np.identity(5)
c = np.full(shape=(3,2),fill_value=5)
# print(c.dtype)
# print(c)
a = np.array([[1,2],[3,4]])
b = np.array(a)  # 重新开辟内存
c = np.asarray(a)  # 引用指向 a
# print(a)
# print(b)
# print(c)
# a[1][1] = 3
# print(a)
# print(b)
# print(c)


# 生成等差数列  
# numpy.linspace(start, stop, num, endpoint, base, dtype)
res = np.linspace(0,20,3,True,retstep=True,dtype=np.float)
# print(res)

# 生成等差数列2
res = np.arange(0,20,2)  # 可以类比range() 使用 
print(res)

# 生成等比数列
# numpy.logspace(start, stop, num, endpoint, base, dtype)
res = np.logspace(1,8,8)
print(res)


[ 0  2  4  6  8 10 12 14 16 18]
[1.e+01 1.e+02 1.e+03 1.e+04 1.e+05 1.e+06 1.e+07 1.e+08]


In [4]:
import numpy as np
a = np.array(0)  # 创建一个数组  0维数组,
print(type(a))  # <class 'numpy.ndarray'>
b = np.array([1,2,3,4])
print(type(b))
print(a.shape)  # ()
print(b.shape)  # (4,)   4行
# 二维数组
c = np.array([[1,2,3,4],[5,6,7,8]])
print(c.shape)  # (2, 4)  2行和4列 的数组
# 三维数组
d = np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(d.shape) # (2, 2, 4) 一般叫做块  2 块 2 行 4 列
# dtype('int32')  范围不同  uint 无符号
print(d.dtype)
e=np.ones(shape=(2,3))
print(e)#[[ 1.  1.  1.]  [ 1.  1.  1.]]  c创建的均为1 float类型
print(e.dtype) # float64

f=np.zeros(shape=(3,2)) #[[ 0.  0.][ 0.  0.][ 0.  0.]]
print(f)
print(f.dtype)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
()
(4,)
(2, 4)
(2, 2, 4)
int64
[[1. 1. 1.]
 [1. 1. 1.]]
float64
[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64


In [5]:
a = np.array([[1,2],[3,4]])

b = np.array(a)
c = np.asarray(b)  # 拷贝引用
a = a+1 
print(a)
print(b)
print(c)


[[2 3]
 [4 5]]
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [6]:

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0,10,11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [8]:
np.logspace(0,100,3)

array([1.e+000, 1.e+050, 1.e+100])

In [9]:
print(np.random.randint(10))
print(np.random.uniform(10))
print(np.random.uniform(1,3,100))
 # 2行3列的随机数
print(np.random.uniform(0,1,(2,3)))  # 2行3列的随机数
print(np.random.rand(10))


3
2.4457404287826234
[1.76474034 1.08879899 2.02309233 1.62709799 1.37102349 2.72575525
 1.92983582 1.78386149 1.44857661 1.02022722 1.35996817 1.45606763
 2.37860465 1.56016805 2.13350755 2.72276104 2.03715432 1.22227512
 2.76473271 2.78325745 1.03680948 2.25008265 2.38928975 1.19240625
 1.57238407 1.48894979 1.20525868 1.90206537 1.71513816 2.23447176
 2.08048581 1.93034134 1.12248454 2.23952933 2.02981405 1.14186445
 2.9636422  1.37642099 1.42866092 2.82883671 2.27689219 2.9780462
 1.37826662 1.65967348 2.52401248 1.9940646  1.43336095 2.18018577
 1.60515631 1.91324952 2.81954134 1.38867517 1.85738783 1.56600973
 2.25987619 1.7363973  1.13111593 1.91068844 1.83806447 1.30741214
 1.51880262 2.37712611 1.4273358  2.14301216 1.59283629 1.94674525
 1.10723182 1.68588172 2.20661579 2.15244212 1.89819813 2.11126879
 1.80595722 1.63707965 2.81998215 2.86865082 1.61209866 2.8011966
 2.09690358 2.8521828  1.33943232 2.8628486  2.32476814 2.86002214
 1.07177803 2.9505329  2.68117178 1.4146451

In [10]:
np.random.rand(10) 

array([0.00104634, 0.09956317, 0.40319599, 0.31964823, 0.04007843,
       0.95363562, 0.77909569, 0.71475695, 0.2313464 , 0.59016856])

In [11]:
a = np.array([[1,2],[3,4]])

b = np.array(a)
c = np.asarray(a)  # 拷贝引用
a[1][1] = 666  
print(a)
print(b)
print(c)

[[  1   2]
 [  3 666]]
[[1 2]
 [3 4]]
[[  1   2]
 [  3 666]]


In [12]:
np.random.normal(0,1.0,(2,3))

array([[ 0.3989554 ,  0.34820816,  0.31245026],
       [-0.34810385,  0.18989232,  1.84078255]])

In [13]:
np.random.standard_normal(size=(2,4))

array([[-1.75251066,  0.10991337, -0.11484767,  0.37459767],
       [ 0.31169321,  0.40076811, -0.09028902, -0.12645448]])

In [14]:
stock_data = np.random.normal(0,1,(500,252*2))
# print(stock_data)
# print(stock_data[0:5][:100])
# stock_data[stock_data>0]
print(stock_data[:10][:200])
print(stock_data[:10,:200])  # pandas 简写
# 是否全部符合传入参数的条件
np.all(stock_data>0)  #False
print("=============")
print(np.unique(stock_data))  # 剔除一样的
print(stock_data.dtype) # float64
stock_data = stock_data.astype(np.float32)  # 改变类型
stock_data = stock_data.astype(np.int64)  # 改变类型
print(stock_data.dtype) # float32
np.unique(stock_data)   # 去重 剩下

[[-1.14913803e+00 -1.08028849e+00  2.71185156e-01 ...  1.88257163e-01
  -9.22014043e-01 -5.54064499e-01]
 [ 5.01858485e-02 -2.41826855e-01 -1.54139572e+00 ... -7.08935985e-01
   2.64777580e-01 -1.14459817e+00]
 [-2.05912519e-01 -4.94518990e-01  1.04592514e-04 ...  2.51332000e-01
  -5.60063593e-01  4.71860080e-01]
 ...
 [-1.29129408e+00  2.76692601e-01  2.04746195e-03 ... -1.81133489e+00
  -9.55351931e-01 -1.55848358e+00]
 [ 4.54792654e-01 -1.90611345e+00 -8.03638769e-01 ...  1.73963000e+00
   6.58434697e-01  8.82708449e-01]
 [ 6.41513457e-01  1.94549153e-01 -7.41096047e-01 ...  9.63228416e-01
   9.03942296e-01  3.35343248e-01]]
[[-1.14913803e+00 -1.08028849e+00  2.71185156e-01 ...  4.20492273e-01
  -5.13963704e-02  9.20900295e-01]
 [ 5.01858485e-02 -2.41826855e-01 -1.54139572e+00 ...  9.95979858e-01
   6.52699021e-01  1.73433346e+00]
 [-2.05912519e-01 -4.94518990e-01  1.04592514e-04 ...  8.58121729e-01
   1.67587427e+00  3.30717027e-01]
 ...
 [-1.29129408e+00  2.76692601e-01  2.0474619

array([-4, -3, -2, -1,  0,  1,  2,  3,  4])

In [18]:
a = np.random.normal(0,1,(500,252*2))
print(stock_data)
# numpy的三元运算符
# 参数1 条件 , 
#  参数 2 条件成立的结果  
#  参数 3 条件不成立的结果
np.where (stock_data>0, 100 , 0)         # 不改变元数据
np.where (np.logical_and(a>0,a<1),100,0) # 不改变元数据
np.where (np.logical_or(a>0,a<-1),100,1) # 不改变原数据
a

[[-0.07938182 -0.00879721  1.5218551  ... -0.22910412  1.13144962
   1.92502123]
 [ 0.63052401  0.88765122 -0.2894014  ...  0.22941797 -0.95896983
   0.43626045]
 [ 0.55084593 -0.18031661 -1.25617782 ...  1.75724861  0.0703419
   0.43608842]
 ...
 [ 0.56553643  1.21044136  0.15766515 ... -0.83769111 -1.41618485
   0.10796181]
 [-0.49965244  0.5649238   0.45170383 ...  1.27151137 -0.02810756
   1.30865482]
 [ 0.06023236  1.73857714 -0.52928425 ...  0.61076913  2.10684735
  -0.08939646]]


array([[-0.41343567,  0.56600074, -1.17734198, ...,  1.76317413,
         0.20172492, -0.03707948],
       [ 1.67212431,  0.89307978, -0.58828407, ...,  0.9664487 ,
        -1.01736998, -0.56847923],
       [-0.43026343, -1.09863362,  0.27082407, ..., -0.89530042,
         1.02406368,  0.33305818],
       ...,
       [ 1.19033589,  2.0509563 , -1.64539547, ..., -0.65606944,
         0.6134278 ,  0.53282584],
       [-0.1749613 , -0.28564798,  0.00652373, ..., -0.23794586,
         0.6488287 ,  0.14124481],
       [-0.08859993, -0.30417019,  0.59020497, ...,  0.35202407,
        -0.86125346, -0.90384956]])

In [16]:
np.min(stock_data[:5,[:5]])
"""方差和标准差表示数据离散程度"""


SyntaxError: invalid syntax (<ipython-input-16-47ba5afcfbd0>, line 1)

In [ ]:
np.min(stock_data[:5,:5])

In [ ]:
np.mean(stock_data[:5,:5],axis=0)

In [ ]:
a = np.array([[1,2,3],[4,5,6]])
np.mean(a)  # 21/6
np.mean(a,axis=1)  # (1+4)/2   列的均值
np.mean(a,axis=0)  # (1+2+3)/2  行的均值
np.argmax(a,axis=1)  # 最大值的索引 行 or 列
a = a+1  # 广播机制
a = a+b  # 对应元素相加



In [21]:
# (m行,l列)*(l行,n列) = (m行,n列)
# (8,2)*(2,1) = (8,1)
a=[[80,86],
[82,80],
[85,78],
[90,90],
[86,82],
[82,90],
[78,80],
[92,94]]
b=[[0.3],[0.7]]
   
cc=np.matmul(a,b)  # 矩阵相乘 获取最终成绩
print(cc)
# help(np.matmul)

[[84.2]
 [80.6]
 [80.1]
 [90. ]
 [83.2]
 [87.6]
 [79.4]
 [93.4]]


In [26]:
a=np.array([[1,2,3,4,5],[6,7,8,9]])
b=np.array([[55,44,33,22,11],[222,333,444,555]])
res=np.vstack((a,b)) # 竖直拼接 列数不变 行数增大
res2=np.hstack((a,b)) # 水平拼接 行数不变 列数增加
print(res)
print(res2)


[[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9])]
 [list([55, 44, 33, 22, 11]) list([222, 333, 444, 555])]]
[list([1, 2, 3, 4, 5]) list([6, 7, 8, 9]) list([55, 44, 33, 22, 11])
 list([222, 333, 444, 555])]


In [ ]:
np.genfromtxt("*.csv",delimiter=",")
# 一般填充列的均值
# 期望为0 方差为1